export const FeaturedMenu = [
    {
        id: 1,
        name: "Chief Burger Meal",
        price: 38,
        offer: "20% off",
        delivery: "25 mins",
        status: "Availale for order now",
        availble: true,
        image: "/images/chiefBurger.png",
    },
    {
        id: 2,
        name: "Jollof Rice",
        price: 38,
        offer: "15% off",
        delivery: "Fast",
        status: "Selling from 12noon WAT",
        availble: false,
        image: "/images/jollofRice.png",
    },
    {
        id: 3,
        name: "Salads",
        price: 38,
        offer: "15% off",
        delivery: "Fast",
        status: "Availale for order now",
        availble: true,
        image: "/images/salads.png",
    },
    {
        id: 4,
        name: "Soups",
        price: 38,
        offer: "15% off",
        delivery: "Fast",
        status: "Selling from 2pm WAT",
        availble: false,
        image: "/images/soups.png",
    },
    {
        id: 5,
        name: "Rotissory Chicken",
        price: 38,
        offer: "15% off",
        delivery: "Fast",
        status: "Availale for order now",
        availble: true,
        image: "/images/chicken.png",
    },
    {
        id: 6,
        name: "Drinks",
        price: 38,
        offer: "15% off",
        delivery: "Fast",
        status: "Selling from 6pm WAT",
        availble: false,
        image: "/images/drinks.png",
    },
    {
        id: 7,
        name: "Ice Cream",
        price: 38,
        offer: "15% off",
        delivery: "Fast",
        status: "Availale for order now",
        availble: true,
        image: "/images/icecream.png",
    },
    {
        id: 8,
        name: "Swallow",
        price: 38,
        offer: "15% off",
        delivery: "Fast",
        status: "Availale for order now",
        availble: true,
        image: "/images/swallow.png",
    },
]